services:

  postgres:
    image: postgres:16-alpine
    container_name: ps-postgres
    restart: unless-stopped

    environment:
      TZ: ${TZ:-Asia/Phnom_Penh}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres

    volumes:
      - ps_postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro

    ports:
      - "127.0.0.1:5436:5432"

    networks:
      - pisethjavaschool-dev-net

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  ps_postgres_data:
    name: ps-postgres-data

networks:
  pisethjavaschool-dev-net:
    external: true